feature/kart-saklama kart saklama eklendi
kahvedigital/iyzico-magento pull request #1
Opened 2016-12-26 01:54 UTC by kahvedigital

2016-12-29 13:58 UTC, heheok requested changes
Değişiklikler yapıldıktan sonra merge edeceğim.

2016-12-29 13:58 UTC, heheok commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/Helper/Data.php
> +    const BASE_URL = "https://sandbox-api.iyzipay.com";
bu değerin hardcoded olmaması gerekmiyor mu? Kullanıcı panelden live seçerse nasıl değişecek?

2016-12-29 13:58 UTC, heheok commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/Model/Cancel/Observer.php
> +                    Mage::getSingleton('core/session')->addError('There are some internal error, please try again.');
Bu mesajların lokalizasyonunu nasıl yapıyoruz? sadece ingilizce mi gözükecek hata?

2016-12-29 13:58 UTC, heheok commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/Model/Method/Abstract.php
> +                        $errorMsg = 'There are some internal error, please try again';
Mesajın türkçesi yok.

2016-12-29 13:58 UTC, heheok commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/Model/Refund/Observer.php
> +                            $errorMessage = 'There are some internal error, please try again.';
mesajın türkçesi yok

2016-12-29 13:58 UTC, heheok commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/controllers/ResponseController.php
> +            return $this->_setErrorRedirect("Invalid Order or Order is already placed");
mesajın türkçesi yok

2016-12-29 13:58 UTC, heheok commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/etc/config.xml
> +                <title>Kreditkarte</title>
bu değişken ne işe yarıyor ve hangi dilde?

2016-12-29 13:58 UTC, heheok commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/etc/system.xml
> +                            <comment><![CDATA[You can get your API ID and Secret Key values from  <a href="https://merchant.iyzipay.com/settings" target="_blank">https://merchant.iyzipay.com/settings
Türkçe olmayacak mı bu kısım?

2016-12-29 13:58 UTC, heheok commented on app/locale/en_US/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Iyzico Basic Setting,Iyzico Setting,
i küçük

2016-12-29 13:58 UTC, heheok commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Enabled,Enabled
Aktif

2016-12-29 13:58 UTC, heheok commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Please make sure that you enter a secure SSL URL.,Bir hata oluştu. SSL'nin etkin olduğundan emin olun.
SSL'in

2016-12-29 13:58 UTC, heheok commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +orderID,siparis no,
sipariş

2016-12-29 13:58 UTC, heheok commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +transaction marked as invalid,işlem geçersiz olarak işaretlenir
işaretlenmiş

2016-12-29 13:58 UTC, heheok commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +This email is already registered as a Iyzico merchant.," ""Bu e-posta zaten Iyzico tüccar olarak tescil edilmiştir."""
iyzico

2016-12-29 13:58 UTC, heheok commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Registration successful. Keys fetched and filled successfully. Please hit Save button to save the settings.," ""Kayıt başarılı. Tuşlar getirilen ve başarıyla dolu. Ayarları kaydetmek için Kaydet tuşu
Kayıt başarılı. Anahtarlar alındı ve başarıyla dolduruldu. Lütfen kaydetmek için Kaydet butonuna basın.

2016-12-29 13:58 UTC, heheok commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Invalid call.," ""Geçersiz arayın."""
Geçersiz İstek

2016-12-29 13:58 UTC, heheok commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Invalid Order or Order is already placed,Geçersiz Sipariş veya sipariş zaten yerleştirilir
Geçersiz Sipariş veya Sipariş daha önce oluşturulmuş.

2017-01-15 23:48 UTC, kahvedigital commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/Helper/Data.php
> +    const BASE_URL = "https://sandbox-api.iyzipay.com";
Sandbox Api Olarak düzeltildi

2017-01-15 23:51 UTC, kahvedigital commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/Model/Cancel/Observer.php
> +                    Mage::getSingleton('core/session')->addError('There are some internal error, please try again.');
Burdaki hata olmayacak hatalara verişmiş ve geçiştirilmiş yani seninde anladığın gibi iyzico dan eğer işlem başarısız ise error mesajı dönmeme ihtimali yok ama yinede bir kontrol yaptırılmış mesela burda ödeme alındımı  durumunun successmi diye sorgulamış böyle bir hata olmasına imkan yok istersen bunların hepsi için bana bir türkçe bir mesaj gönder hepsine aynısını yazıyım ben bunları gördüm fakat güncellemedim önemsiz diye

2017-01-15 23:51 UTC, kahvedigital commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/Model/Method/Abstract.php
> +                        $errorMsg = 'There are some internal error, please try again';
Burdaki hata olmayacak hatalara verişmiş ve geçiştirilmiş yani seninde anladığın gibi iyzico dan eğer işlem başarısız ise error mesajı dönmeme ihtimali yok ama yinede bir kontrol yaptırılmış mesela burda ödeme alındımı  durumunun successmi diye sorgulamış böyle bir hata olmasına imkan yok istersen bunların hepsi için bana bir türkçe bir mesaj gönder hepsine aynısını yazıyım ben bunları gördüm fakat güncellemedim önemsiz diye

2017-01-15 23:52 UTC, kahvedigital commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/controllers/ResponseController.php
> +            return $this->_setErrorRedirect("Invalid Order or Order is already placed");
Mesajın türkçesi türkçe dosyasında mevcut.

2017-01-15 23:54 UTC, kahvedigital commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/etc/system.xml
> +                            <comment><![CDATA[You can get your API ID and Secret Key values from  <a href="https://merchant.iyzipay.com/settings" target="_blank">https://merchant.iyzipay.com/settings
Bu kısımı ilk yazmaya başladığımda gördüm fakat commet bölümüne php fonksiyon almıyor ve çok araştırdım bu bölümün dil seçeneğine ceviremiyoruz istersen burda direk mesajı türkçe yayınlarız.

2017-01-15 23:56 UTC, kahvedigital commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/etc/config.xml
> +                <title>Kreditkarte</title>
Bu modülün orjinalinde var şöyleki burda aslında title belirliyor fakat bunu kullanmıyor direkt isim olarak echo ettiriyor ve türkçe side var , ben title bölümünü silip riske atmak istemedim belki değişik versiyonlarda olmadığında hata alıyor olabilir diye.

2017-01-15 23:56 UTC, kahvedigital commented on app/locale/en_US/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Iyzico Basic Setting,Iyzico Setting,
Düzeltildi

2017-01-15 23:56 UTC, kahvedigital commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Please make sure that you enter a secure SSL URL.,Bir hata oluştu. SSL'nin etkin olduğundan emin olun.
Düzeltildi

2017-01-15 23:56 UTC, kahvedigital commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +orderID,siparis no,
Düzeltildi

2017-01-15 23:57 UTC, kahvedigital commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +transaction marked as invalid,işlem geçersiz olarak işaretlenir
Düzeltildi

2017-01-15 23:57 UTC, kahvedigital commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +This email is already registered as a Iyzico merchant.," ""Bu e-posta zaten Iyzico tüccar olarak tescil edilmiştir."""
Düzeltildi

2017-01-15 23:57 UTC, kahvedigital commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Registration successful. Keys fetched and filled successfully. Please hit Save button to save the settings.," ""Kayıt başarılı. Tuşlar getirilen ve başarıyla dolu. Ayarları kaydetmek için Kaydet tuşu
Düzeltildi

2017-01-15 23:57 UTC, kahvedigital commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Invalid call.," ""Geçersiz arayın."""
Düzeltildi

2017-01-15 23:57 UTC, kahvedigital commented on app/locale/tr_TR/IyzicoCheckoutForm_IyzicoCheckoutForm.csv
> +Invalid Order or Order is already placed,Geçersiz Sipariş veya sipariş zaten yerleştirilir
Düzeltildi

2017-01-16 00:00 UTC, kahvedigital commented on app/code/community/IyzicoCheckoutForm/IyzicoCheckoutForm/Model/Cancel/Observer.php
> +                    Mage::getSingleton('core/session')->addError('There are some internal error, please try again.');
Birde bu hataların bir çoğunu test etme imkanımız bile yok :) yazdığım kodu test edemeyeceğim hatta bazı yerde hatanın kaynağını bile bilemeyiz genel bir hata yazdırılmalı bu sebeplerden dolayı düzenlemedim sanırım senin görmediğin bir kaç yerde de var bence önemsiz ama yine son karar sizin.

2017-01-16 07:30 UTC, heheok approved these changes

2017-01-16 07:31 UTC, merged